[colors.primary]
background = "#000000"
foreground = "#f2f4f8"
dim_foreground = "#b6b8bb"
bright_foreground = "#f9fbff"
[window]
dimensions = { columns = 120, lines = 32 }
decorations = "Transparent"
dynamic_padding = true
title = "Alacritty"
opacity = 0.5
dynamic_title = true
[cursor]
style = { shape = "Beam", blinking = "Never" }
[font]
normal = { family = "Fira Code Nerd Font", style = "Regular" }
bold = { family = "Fira Code Nerd Font", style = "Regular" }
italic = { family = "Fira Code Nerd Font", style = "Regular" }
bold_italic = { family = "Fira Code Nerd Font", style = "Regular" }
